# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OnTrackApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OnTrackApp
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  

  target 'OnTrackAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
