// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/mikaelkristiansson/Sites/ontrack/OnTrackApp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/mikaelkristiansson/Sites/ontrack/OnTrackApp/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/mikaelkristiansson/Sites/ontrack/OnTrackApp/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('OnTrackApp', appParameters);
});